pipeline {
  agent any

  stages {
    stage("Initial Cleanup") {
      steps {
        deleteDir()
      }
    }

    stage("Build") {
      steps {
        sh 'echo "Building Stage"'
      }
    }

    stage("Test") {
      steps {
        sh 'echo "Testing Stage"'
      }
    }

    stage("Package") {
      steps {
        sh 'echo "Packaging App"'
      }
    }

    stage("Deploy") {
      steps {
        sh 'echo "Deploy to Dev"'
      }
    }

    stage("Clean up") {
      steps {
        cleanWS()
      }
    }
  }
}
