pipeline {
    agent any
  
    stages {
        stage('Initial cleanup') {
            steps {
                deleteDir()
            }
        }
        
        stage('Build') {
            steps {
                echo 'Building Stage'
                // Add your build steps here
            }
        }

        stage('Test') {
            steps {
                echo 'Testing Stage'
                // Add your test steps here
            }
        }

        stage('Package') {
            steps {
                echo 'Packaging App'
                // Add your packaging steps here
            }
        }
    
        stage('Deploy') {
            steps {
                echo 'Deploying to Dev'
                // Add your deployment steps here
            }
        }
        
        stage('Cleanup') {
            steps {
                cleanWs()
            }
        }
    }
}